### ISSUE TITLE
Complete coverage of csv files/years on edge results

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#5]
This issue is to report that there may be incomplete coverage of csv files/years on edge results that are returned in ICEES KG answer sets. To be fair, the issue may require more extensive testing before raising the issue to a formal 'issue', per se, but it's worth troubleshooting.

For example, I'd expect to see data from every available year (2010-2019) returned for the following queries:

[MONDO0004979_RWE_ChemicalEntity_2_response_1662733145870](https://drive.google.com/file/d/1n-igVOWYnXjbDsnHcuAzhaBSvHJWOfNx/view?usp=sharing) (new test)
Missing 2011, 2017

[MONDO0004979_RWE_ChemicalEntity_response_1662044955494](https://drive.google.com/file/d/15WHBsYGs1rG0RXgPDfA9ljCiKL01Qrps/view?usp=sharing) (prior test)
Missing asthma 2010, 2017

**Comment by maximusunc** [comment]
This was a bug/"feature" in KGX that I fixed locally. Basically, KGX was doing a naive edge merge based on subject/predicate/object, but since our data is mainly temporal, it was overwriting many edges. My fix was to make KGX treat every edge as unique so that it wouldn't merge anything. I've chatted with KGX folks and let them know our use case and they are thinking about ways to handle these types of cases in the future.
